-- THE FOLLOWING TAKES AROUND 15 MINUTES TO RUN, DATABASE IN ELASTICPOOL, PUSHING DTU % TO AROUND 70% WITH ONE INSTANCE OF THE QUERY RUNNING

SELECT SUM(POWER(ABS(CAST(CHECKSUM(NEWID()) AS BIGINT)) % 10000, 2)) AS Result
FROM sys.all_columns a
CROSS JOIN sys.all_columns b
CROSS JOIN sys.all_columns c